/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "chatapp.h"

void chatapp_prog_1(char *host, char *msg)
{
	CLIENT *clnt;
	char **result_1;
	data chat_1_arg;

#ifndef DEBUG
	clnt = clnt_create(host, CHATAPP_PROG, CHATAPP_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	chat_1_arg.msg = msg;
	result_1 = chat_1(&chat_1_arg, clnt);
	if (result_1 == (char **)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Server Response: %s\n", *result_1);
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;

	if (argc < 3)
	{
		printf("usage: %s server_host message\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	chatapp_prog_1(host, argv[2]);
	exit(0);
}
