/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "chatapp.h"

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->msg, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
