/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CHATAPP_H_RPCGEN
#define _CHATAPP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct target {
	char *ip;
	int port;
};
typedef struct target target;

#define CHATAPP_PROG 0x23452222
#define CHATAPP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define chatapp 1
extern  int * chatapp_1(target *, CLIENT *);
extern  int * chatapp_1_svc(target *, struct svc_req *);
extern int chatapp_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define chatapp 1
extern  int * chatapp_1();
extern  int * chatapp_1_svc();
extern int chatapp_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_target (XDR *, target*);

#else /* K&R C */
extern bool_t xdr_target ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CHATAPP_H_RPCGEN */
