/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "chatapp.h"

bool_t
xdr_target (XDR *xdrs, target *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->ip, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->port))
		 return FALSE;
	return TRUE;
}
