/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "chatapp.h"

char **
chat_1_svc(data *argp, struct svc_req *rqstp)
{
	static char *result;
	char msg[80];
	result = argp->msg;
	printf("Client: %s\n", result);
	printf("Server: ");
	gets(msg);
	strcpy(argp->msg, msg);
	result = argp->msg;
	return &result;
}
