/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <time.h>
#include "datetime.h"

char **
datetime_1_svc(void *argp, struct svc_req *rqstp)
{
	static char *result;

	time_t t; // not a primitive datatype
	time(&t);
	result = ctime(&t);

	printf("Got request at: %s", result);

	return &result;
}
