/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "factorial.h"

int *factorial_1_svc(number *argp, struct svc_req *rqstp)
{
	static int result;

	// MY CODE START

	printf("The number received is: %d\n", argp->num);
	int fact = 1;

	// shows error if the user enters a negative integer
	if (argp->num < 0)
	{
		fact = -1;
	}
	else
	{
		for (int i = 1; i <= argp->num; ++i)
		{
			fact *= i;
		}
		// printf("Factorial of %d = %llu", n, fact);
	}

	result = fact;

	// MY CODE END

	return &result;
}
